version: '3.3'
services:
  webapp:
    image: stijnpietersnmct/ff02-webapp
    build: ./web
    command: uwsgi --ini app.ini
    expose:
      - 5000
    depends_on:
      - influx
  nginx:
    image: stijnpietersnmct/ff02-nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - webapp
  influx:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb

